image: alpine:lastest

before_script:
  - apk add --update --no-cache openssh sshpass

actualizar:
  stage: deploy
  script:
  - sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no -p $PORT $USERNAME@$HOST 'cd blackend && git pull && docker compose --file ./Docker-compose.yml up --build -d'
#  - cd blackend-observatorio
#  - git pull
#  - docker compose --file ./Docker-compose.yml up --build -d
  only:
  - main
